In [10]:
from pytorch.subglottal_pressure import subglottal_pressure
import torch

test_input = torch.tensor([0.0, 0.25, 0.5, 0.75, 1.0])
python_output = subglottal_pressure(test_input)
print(python_output)

'''
matlab values:
x = [0.0, 0.25, 0.5, 0.75, 1.0];
y = subglottal_pressure(x)
y = 101.33    575.99   1050.66   1525.33   2000.00
'''

matlab_output = torch.tensor([101.33, 575.99, 1050.66, 1525.33, 2000.00])

# .allclose checks if all elements of two tensors are close within a tolerance of 1e-2
print(torch.allclose(python_output, matlab_output, atol=1e-2))

tensor([ 101.3250,  575.9938, 1050.6625, 1525.3313, 2000.0000])
True


In [11]:
from pytorch.glottal_area import glottal_area

PCAIA_test = torch.tensor([0.0, 0.5, 1.0])
TA_test = torch.tensor([0.0, 0.5, 1.0])

python_output = glottal_area(PCAIA_test, TA_test)
print(python_output)

'''
matlab values:
PCAIA_activity = [0.0, 0.5, 1.0];
TA_activity = [0.0, 0.5, 1.0];
y = glottal_area(PCAIA_activity, TA_activity)
y = 6.3500e-07   3.1750e-07            0
'''

matlab_output = torch.tensor([6.35e-7, 3.175e-7, 0.0])
print(torch.allclose(python_output, matlab_output, atol=1e-8))

tensor([6.3500e-07, 3.1750e-07, 0.0000e+00])
True


In [15]:
from pytorch.impingement_length import impingement_length
CT_test = torch.tensor([0.0, 0.5, 1.0])
TA_test = torch.tensor([0.0, 0.5, 1.0])

python_output = impingement_length(CT_test, TA_test)
print(python_output)

'''
matlab values:
CT_activity = [0.0, 0.5, 1.0];
TA_activity = [0.0, 0.5, 1.0];
y = impingement_length(CT_activity, TA_activity)
y = 1.0000e-04   6.3200e-04   1.1640e-03
'''

matlab_output = torch.tensor([1.0e-4, 6.32e-4, 1.164e-3])
print(torch.allclose(python_output, matlab_output, atol=1e-8))

# other case
CT_test = torch.tensor([0.0, 1.0, 0.0, 1.0])
TA_test = torch.tensor([0.0, 0.0, 1.0, 1.0])

python_output = impingement_length(CT_test, TA_test)
print(python_output)

matlab_output = torch.tensor([1.0000e-04, 1.5000e-03, -2.3600e-04, 1.1640e-03])
print(torch.allclose(python_output, matlab_output, atol=1e-8))


tensor([1.0000e-04, 6.3200e-04, 1.1640e-03])
True
tensor([ 1.0000e-04,  1.5000e-03, -2.3600e-04,  1.1640e-03])
True


In [1]:
from pytorch.jet_speed import jet_speed_from_pressure
import torch

glottal_area_test = torch.tensor([1e-7, 3e-7, 6e-7])
pressure_test = torch.tensor([200.0, 1000.0, 2000.0])

python_output = jet_speed_from_pressure(glottal_area_test, pressure_test)
print(python_output)

'''
matlab values:
glottal_area = [1e-7, 3e-7, 6e-7];
pressure = [200.0, 1000.0, 2000.0];
y = jet_speed(glottal_area, pressure, 'p')
y = 12.764   40.370   71.812
'''

matlab_output = torch.tensor([12.764, 40.370, 71.812])
print(torch.allclose(python_output, matlab_output, atol=1e-2))

tensor([12.7635, 40.3701, 71.8118])
True


In [2]:
from pytorch.jet_speed import jet_speed_from_airflow

glottal_area_test = torch.tensor([1e-7, 3e-7, 6e-7])
airflow_test = torch.tensor([1e-5, 5e-5, 1e-4])

python_output = jet_speed_from_airflow(glottal_area_test, airflow_test)
print(python_output)

'''
matlab values:
glottal_area = [1e-7, 3e-7, 6e-7];
airflow = [1e-5, 5e-5, 1e-4];
y = jet_speed(glottal_area, airflow, 'f')
y = 100.00   166.67   166.67
'''

matlab_output = torch.tensor([100.00, 166.67, 166.67])
print(torch.allclose(python_output, matlab_output, atol=1e-2))

tensor([100.0000, 166.6667, 166.6667])
True


In [3]:
from pytorch.airflow import airflow

pressure_test = torch.tensor([200.0, 1000.0, 2000.0])
glottal_area_test = torch.tensor([1e-7, 3e-7, 6e-7])

python_output = airflow(pressure_test, glottal_area_test)
print(python_output)

'''
matlab values:
pressure = [200.0, 1000.0, 2000.0];
glottal_area = [1e-7, 3e-7, 6e-7];
y = airflow(pressure, glottal_area)
y = 8.0600e-07   7.9668e-06   2.8891e-05
'''

matlab_output = torch.tensor([8.0600e-07, 7.9668e-06, 2.8891e-05])
print(torch.allclose(python_output, matlab_output, atol=1e-8))

tensor([8.0600e-07, 7.9668e-06, 2.8891e-05])
True
