In [10]:
from pytorch.subglottal_pressure import subglottal_pressure
import torch

test_input = torch.tensor([0.0, 0.25, 0.5, 0.75, 1.0])
python_output = subglottal_pressure(test_input)
print(python_output)

'''
matlab values:
x = [0.0, 0.25, 0.5, 0.75, 1.0];
y = subglottal_pressure(x)
y = 101.33    575.99   1050.66   1525.33   2000.00
'''

matlab_output = torch.tensor([101.33, 575.99, 1050.66, 1525.33, 2000.00])

# .allclose checks if all elements of two tensors are close within a tolerance of 1e-2
print(torch.allclose(python_output, matlab_output, atol=1e-2))

tensor([ 101.3250,  575.9938, 1050.6625, 1525.3313, 2000.0000])
True


In [11]:
from pytorch.glottal_area import glottal_area

PCAIA_test = torch.tensor([0.0, 0.5, 1.0])
TA_test = torch.tensor([0.0, 0.5, 1.0])

python_output = glottal_area(PCAIA_test, TA_test)
print(python_output)

'''
matlab values:
PCAIA_activity = [0.0, 0.5, 1.0];
TA_activity = [0.0, 0.5, 1.0];
y = glottal_area(PCAIA_activity, TA_activity)
y = 6.3500e-07   3.1750e-07            0
'''

matlab_output = torch.tensor([6.35e-7, 3.175e-7, 0.0])
print(torch.allclose(python_output, matlab_output, atol=1e-8))

tensor([6.3500e-07, 3.1750e-07, 0.0000e+00])
True


In [15]:
from pytorch.impingement_length import impingement_length
CT_test = torch.tensor([0.0, 0.5, 1.0])
TA_test = torch.tensor([0.0, 0.5, 1.0])

python_output = impingement_length(CT_test, TA_test)
print(python_output)

'''
matlab values:
CT_activity = [0.0, 0.5, 1.0];
TA_activity = [0.0, 0.5, 1.0];
y = impingement_length(CT_activity, TA_activity)
y = 1.0000e-04   6.3200e-04   1.1640e-03
'''

matlab_output = torch.tensor([1.0e-4, 6.32e-4, 1.164e-3])
print(torch.allclose(python_output, matlab_output, atol=1e-8))

# other case
CT_test = torch.tensor([0.0, 1.0, 0.0, 1.0])
TA_test = torch.tensor([0.0, 0.0, 1.0, 1.0])

python_output = impingement_length(CT_test, TA_test)
print(python_output)

matlab_output = torch.tensor([1.0000e-04, 1.5000e-03, -2.3600e-04, 1.1640e-03])
print(torch.allclose(python_output, matlab_output, atol=1e-8))


tensor([1.0000e-04, 6.3200e-04, 1.1640e-03])
True
tensor([ 1.0000e-04,  1.5000e-03, -2.3600e-04,  1.1640e-03])
True
